name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: realabbas/Github-Actions-React-Native@v1.1.2 
      - name: React Native Android Build APK
